baseURL = "https://nusdistsys.github.io/"
languageCode = "en-us"
title = "6.824 DYOM"
[menu]

  [[menu.main]]
    identifier = "Labs"
    name = "Labs"
    url = "/labs/"
    weight = -110

  [[menu.main]]
    identifier = "Notes"
    name = "Notes"
    url = "/notes/"
    weight = -100
  
  [[menu.main]]
    identifier = "Summer"
    name = "Summer"
    url = "/summer/"
    weight = -100

[markup.goldmark.renderer]
unsafe= true